[nvmesh_solar]
extends = nrf52_base
board = nvmesh_solar_node
platform_packages = framework-arduinoadafruitnrf52
board_build.ldscript = boards/nrf52840_s140_v6.ld
build_flags =  ${nrf52_base.build_flags}
  -I src/helpers/nrf52
  -I lib/nrf52/s140_nrf52_6.1.1_API/include
  -I lib/nrf52/s140_nrf52_6.1.1_API/include/nrf52
  -I variants/nvmesh_solar
  -D RADIO_CLASS=CustomSX1262
  -D WRAPPER_CLASS=CustomSX1262Wrapper
  -D LORA_TX_POWER=22
  -D SX126X_CURRENT_LIMIT=140
  -D SX126X_RX_BOOSTED_GAIN=1
  -D ENV_INCLUDE_INA219=1
  -D P_LORA_TX_LED=40
  -D INA219_INVERT_CURRENT
  -D INA219_BATT_VOLTAGE
  -D NO_INA219_WATTS
build_src_filter = ${nrf52_base.build_src_filter}
  +<helpers/*.cpp>
  +<helpers/sensors>
  +<../variants/nvmesh_solar>
lib_deps =
  ${nrf52_base.lib_deps}
  rweather/Crypto @ ^0.4.0
  stevemarple/MicroNMEA @ ^2.0.6
  adafruit/Adafruit NeoPixel@^1.10.0
  adafruit/Adafruit INA219 @ ^1.2.3
;  https://github.com/NMIoT/meshsolar/archive/dfc5330dad443982e6cdd37a61d33fc7252f468b.zip
debug_tool = jlink
upload_protocol = nrfutil

[env:nvmesh_solar_repeater]
extends = nvmesh_solar
build_src_filter = ${nvmesh_solar.build_src_filter}
  +<../examples/simple_repeater>

build_flags =
  ${nvmesh_solar.build_flags}
  -D ADVERT_NAME='"nvme.sh Repeater"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D MAX_NEIGHBOURS=50
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1

[env:nvmesh_solar_room_server]
extends = nvmesh_solar
build_src_filter = ${nvmesh_solar.build_src_filter}
  +<../examples/simple_room_server>
build_flags =
  ${nvmesh_solar.build_flags}
  -D ADVERT_NAME='"nvme.sh Room"'
  -D ADVERT_LAT=0.0
  -D ADVERT_LON=0.0
  -D ADMIN_PASSWORD='"password"'
  -D ROOM_PASSWORD='"hello"'
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1

[env:nvmesh_solar_companion_radio_ble]
extends = nvmesh_solar
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags =
  ${nvmesh_solar.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
  -D BLE_PIN_CODE=123456
;  -D BLE_DEBUG_LOGGING=1
  -D OFFLINE_QUEUE_SIZE=256
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${nvmesh_solar.build_src_filter}
  +<helpers/nrf52/SerialBLEInterface.cpp>
  +<../examples/companion_radio/*.cpp>
lib_deps =
  ${nvmesh_solar.lib_deps}
  densaugeo/base64 @ ~1.4.0

[env:nvmesh_solar_companion_radio_usb]
extends = nvmesh_solar
board_build.ldscript = boards/nrf52840_s140_v6_extrafs.ld
board_upload.maximum_size = 712704
build_flags =
  ${nvmesh_solar.build_flags}
  -D MAX_CONTACTS=350
  -D MAX_GROUP_CHANNELS=40
;  -D BLE_PIN_CODE=123456
;  -D BLE_DEBUG_LOGGING=1
;  -D MESH_PACKET_LOGGING=1
;  -D MESH_DEBUG=1
build_src_filter = ${nvmesh_solar.build_src_filter}
  +<helpers/nrf52/*.cpp>
  +<../examples/companion_radio/*.cpp>
lib_deps =
  ${nvmesh_solar.lib_deps}
  densaugeo/base64 @ ~1.4.0